---
- hosts: centos
  become: yes
  ignore_errors: yes
  tasks:
 
  - name: install java
    yum: 
      name: java-1.8.0-openjdk.x86_64
      state: installed
 
  - name: key pair jenkins
    rpm_key:
      key: https://jenkins-ci.org/redhat/jenkins-ci.org.key
      state: present
    tags: key

  - name: jenkins repository
    get_url:
      url: http://pkg.jenkins-ci.org/redhat/jenkins.repo
      dest: /etc/yum.repos.d/jenkins.repo
    tags: repo

  - name: install jenkins
    yum:
      name: jenkins
      state: present
      update_cache: yes

        
